#-------------------------------------------------------------------------
#
# Makefile for src/pl/pltsql (A procedural language compatible with T-SQL)
#
# Copyright (c) 1994, Regents of the University of California
# Copyright (c) 2011-2012 OpenSCG, Inc.  All rights reserved.
#
# src/pl/pltsql/Makefile
#
#-------------------------------------------------------------------------

subdir = src/pl/pltsql
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

all install installdirs uninstall distprep clean distclean maintainer-clean coverage:
	$(MAKE) -C src $@
