#-------------------------------------------------------------------------
#
# Makefile for src/pl/pltsql (TSQL-compatible procedural language)
#
# Portions Copyright (c) 2011-2012, TPOSTGRES.  All rights reserved.
#
# Copyright (c) 1994, Regents of the University of California
#
# src/pl/pltsql/Makefile
#
#-------------------------------------------------------------------------

subdir = src/pl/pltsql
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

all install installdirs uninstall distprep clean distclean maintainer-clean coverage:
	$(MAKE) -C src $@
