#-------------------------------------------------------------------------
#
# Makefile for src/pl/plpgsql (PostgreSQL's SQL procedural language)
#
# Copyright (c) 1994, Regents of the University of California
# Copyright (c) 2011-2012 OpenSCG, Inc.  All rights reserved.
#
# src/pl/plpgsql/Makefile
#
#-------------------------------------------------------------------------

subdir = src/pl/plpgsql
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

all install installdirs uninstall distprep clean distclean maintainer-clean coverage:
	$(MAKE) -C src $@
